Importamos las librerías Pandas y Numpy

In [52]:
import pandas as pd
import numpy as np

### Step 2. Tomaremos el fichero en [esta URL](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) y lo leeremos como un dataframe.

Pista: [read_csv](https://numpy.org/doc/stable/user/absolute_beginners.html#importing-and-exporting-a-csv)

In [103]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
data=pd.read_csv("chipotle.csv",sep="\t")
data

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [104]:
data.head(100)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
95,42,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
96,42,1,Chips and Guacamole,NaN,$4.45
97,43,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.75
98,43,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
99,44,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$8.75

### Step 3. Veamos los tipos de datos. ¿Podríamos obtener el producto de mayor precio?

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [ ]:
# gnereo floats de item
data["itempricefloat"]=(data["item_price"].str.replace("$", "").astype(float))#str te da acceso al objeto y la serie
#genero de cada iimpes
data["individual_price"]=data["itempricefloat"]/data["quantity"]
data["item_name"][(data["itempricefloat"].idxmax())]

'Chips and Fresh Tomato Salsa'

In [107]:
valor_maximo=data["itempricefloat"].max()
condicion=(data["itempricefloat"]==valor_maximo)

data[condicion]

,order_id,quantity,item_name,choice_description,item_price,itempricefloat,individual_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25,2.95

### Step 4. ¿Qué productos cuestan más de $10?

In [58]:
data["item_name"][data["itempricefloat"]>10].unique()

array(['Chicken Bowl', 'Steak Burrito', 'Chicken Burrito',
       'Barbacoa Bowl', 'Veggie Burrito', 'Veggie Bowl',
       'Chicken Soft Tacos', 'Steak Bowl', 'Carnitas Burrito',
       'Carnitas Bowl', 'Barbacoa Burrito', 'Chicken Salad Bowl',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chicken Crispy Tacos', 'Chicken Salad', 'Steak Salad Bowl',
       'Bowl', 'Veggie Soft Tacos', 'Barbacoa Soft Tacos',
       'Carnitas Crispy Tacos', 'Carnitas Salad Bowl',
       'Barbacoa Salad Bowl', 'Chips and Fresh Tomato Salsa',
       'Steak Soft Tacos', 'Carnitas Soft Tacos', 'Steak Crispy Tacos',
       'Chips and Guacamole', '6 Pack Soft Drink', 'Bottled Water',
       'Side of Chips'], dtype=object)

In [59]:
condicion=(data["itempricefloat"]>10)
data[condicion]
len(data[condicion])

1130

### Step 4.1: ¿Y cuántos pedidos se han hecho con un producto de más de 10$? ¿Es lo mismo?

In [60]:
condicion=data["itempricefloat"]>=10
data[condicion]["order_id"]

4          2
5          3
7          4
13         7
23        12
        ...
4610    1830
4611    1830
4617    1833
4618    1833
4619    1834
Name: order_id, Length: 1130, dtype: int64

### Step 4.2: ¿Y cuántos pedidos se han hecho de más de 10$? ¿Es lo mismo?

In [61]:
#hacerlo con group by
data_id10=data.groupby("order_id")["itempricefloat"].sum()
data_id10

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: itempricefloat, Length: 1834, dtype: float64

'for id in da\n\ncondicion=(data[]["itempricefloat"].sum()>=10)\n\nlen(data[condicion])'

### Step 4.3: ¿Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? ¿Es lo mismo?

In [67]:
condicion=data["individual_price"]>=10
data[condicion]["order_id"]

5          3
7          4
13         7
23        12
39        19
        ...
4610    1830
4611    1830
4617    1833
4618    1833
4619    1834
Name: order_id, Length: 1034, dtype: int64

### Step 5. ¿Qué precio tiene cada producto en distintos pedidos? ¿Hay productos con varios precios?

In [ ]:
data_name=data.groupby("item_name")["individual_price"].unique()
print(data_name, "Si")

item_name
6 Pack Soft Drink                                                                   [6.49]
Barbacoa Bowl                                      [11.75, 9.25, 8.99, 11.48, 8.69, 11.49]
Barbacoa Burrito                                   [8.99, 9.25, 11.75, 11.08, 8.69, 11.48]
Barbacoa Crispy Tacos                                           [11.75, 9.25, 11.48, 8.99]
Barbacoa Salad Bowl                                                          [11.89, 9.39]
Barbacoa Soft Tacos                                             [9.25, 8.99, 11.75, 11.48]
Bottled Water                                                                  [1.09, 1.5]
Bowl                                                             [7.3999999999999995, 7.4]
Burrito                                                                              [7.4]
Canned Soda                                                                         [1.09]
Canned Soft Drink                                                                   [1.25]
Carnitas Bowl                                            [8.99, 11.75, 9.25, 11.48, 11.08]
Carnitas Burrito                                   [8.99, 9.25, 11.75, 11.48, 11.08, 8.69]
Carnitas Crispy Tacos                                                  [9.25, 11.75, 8.99]
Carnitas Salad                                                                      [8.99]
Carnitas Salad Bowl                                                          [11.89, 9.39]
Carnitas Soft Tacos                                                    [9.25, 8.99, 11.75]
Chicken Bowl                             [8.49, 10.98, 11.25, 8.75, 10.979999999999999,...
Chicken Burrito                                    [8.49, 10.98, 8.75, 11.25, 10.58, 8.19]
Chicken Crispy Tacos                                            [8.75, 11.25, 8.49, 10.98]
Chicken Salad                                                          [10.98, 8.49, 8.19]
Chicken Salad Bowl                                                           [8.75, 11.25]
Chicken Soft Tacos                                              [8.75, 11.25, 8.49, 10.98]
Chips                                                                         [2.15, 1.99]
Chips and Fresh Tomato Salsa                                            [2.39, 2.95, 2.29]
Chips and Guacamole                                          [4.45, 3.99, 4.0, 3.89, 4.25]
Chips and Mild Fresh Tomato Salsa                                                    [3.0]
Chips and Roasted Chili Corn Salsa                                                  [2.95]
Chips and Roasted Chili-Corn Salsa                                                  [2.39]
Chips and Tomatillo Green Chili Salsa                                               [2.95]
Chips and Tomatillo Red Chili Salsa                                                 [2.95]
Chips and Tomatillo-Green Chili Salsa                                               [2.39]
Chips and Tomatillo-Red Chili Salsa                                                 [2.39]
Crispy Tacos                                                                         [7.4]
Izze                                                                                [3.39]
Nantucket Nectar                                                                    [3.39]
Salad                                                                                [7.4]
Side of Chips                                                   [1.69, 1.6900000000000002]
Steak Bowl                                         [8.99, 11.75, 11.48, 9.25, 11.08, 8.69]
Steak Burrito                                      [11.75, 9.25, 8.99, 11.48, 11.08, 8.69]
Steak Crispy Tacos                                               [9.25, 8.99, 8.69, 11.75]
Steak Salad                                                                   [8.99, 8.69]
Steak Salad Bowl                                                             [11.89, 9.39]
Steak Soft Tacos                                                [9.25, 8.99, 11.75, 11.48]
Veggie Bowl                                                     [11.25, 8.49, 8.75, 10.98]
Veggie Burrito                                                  [11.25, 8.49, 10.98, 8.75]
Veggie Crispy Tacos                                                                 [8.49]
Veggie Salad                                                                        [8.49]
Veggie Salad Bowl                                                            [11.25, 8.75]
Veggie Soft Tacos                                                      [11.25, 8.75, 8.49]
Name: individual_price, dtype: object

### Step 6. Ordena el dataframe en base al nombre de producto (item name)

In [112]:
sorted(data.groupby("item_name"))

[('6 Pack Soft Drink',
        order_id  quantity          item_name choice_description item_price  \
  298        129         1  6 Pack Soft Drink           [Sprite]     $6.49
  341        148         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  357        154         1  6 Pack Soft Drink             [Coke]     $6.49
  388        168         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  417        182         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  553        230         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  639        264         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  721        298         1  6 Pack Soft Drink           [Nestea]     $6.49
  743        306         1  6 Pack Soft Drink             [Coke]     $6.49
  879        363         1  6 Pack Soft Drink             [Coke]     $6.49
  1026       422         1  6 Pack Soft Drink           [Sprite]     $6.49
  1051       432         1  6 Pack Soft Drink             [Coke]     $6.49
  1124       465         1  6 Pack Soft Drink             [Coke]     $6.49
  1167       481         1  6 Pack Soft Drink             [Coke]     $6.49
  1260       511         1  6 Pack Soft Drink             [Coke]     $6.49
  1279       520         1  6 Pack Soft Drink           [Sprite]     $6.49
  1392       566         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  1755       708         1  6 Pack Soft Drink             [Coke]     $6.49
  1758       709         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  1849       749         1  6 Pack Soft Drink             [Coke]     $6.49
  1860       754         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  1916       774         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  1922       776         1  6 Pack Soft Drink             [Coke]     $6.49
  1937       784         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  1976       798         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  2108       849         1  6 Pack Soft Drink             [Coke]     $6.49
  2232       899         1  6 Pack Soft Drink             [Coke]     $6.49
  2374       945         1  6 Pack Soft Drink           [Sprite]     $6.49
  2389       949         1  6 Pack Soft Drink             [Coke]     $6.49
  2713      1076         1  6 Pack Soft Drink             [Coke]     $6.49
  2793      1109         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  2860      1136         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  3010      1196         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  3132      1248         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  3141      1253         1  6 Pack Soft Drink         [Lemonade]     $6.49
  3389      1360         2  6 Pack Soft Drink        [Diet Coke]    $12.98
  3422      1373         1  6 Pack Soft Drink             [Coke]     $6.49
  3600      1443         1  6 Pack Soft Drink             [Coke]     $6.49
  3614      1448         1  6 Pack Soft Drink           [Nestea]     $6.49
  3633      1454         1  6 Pack Soft Drink             [Coke]     $6.49
  3693      1480         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  3766      1508         1  6 Pack Soft Drink             [Coke]     $6.49
  3789      1517         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  3806      1525         1  6 Pack Soft Drink           [Sprite]     $6.49
  3836      1537         1  6 Pack Soft Drink             [Coke]     $6.49
  3875      1554         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  3886      1558         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  4169      1664         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  4174      1666         1  6 Pack Soft Drink             [Coke]     $6.49
  4359      1741         1  6 Pack Soft Drink             [Coke]     $6.49
  4363      1742         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  4522      1798         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  4527      1800         1  6 Pack Soft Drink        [Diet Coke]     $6.49
  4535      1803         1  6 Pack Soft Drink         [Lemonade]     $6.49

        itempricefloat  individual_price
  298             6.49              6.49
  341             6.49              6.49
  357             6.49              6.49
  388             6.49              6.49
  417             6.49              6.49
  553             6.49              6.49
  639             6.49              6.49
  721             6.49              6.49
  743             6.49              6.49
  879             6.49              6.49
  1026            6.49              6.49
  1051            6.49              6.49
  1124            6.49              6.49
  1167            6.49              6.49
  1260            6.49              6.49
  1279            6.49              6.49
  1392            6.49              6.49
  1755            6.49              6.49
  1758            6.49              6.49
  1849            6.49              6.49
  1860            6.49              6.49
  1916            6.49              6.49
  1922            6.49              6.49
  1937            6.49              6.49
  1976            6.49              6.49
  2108            6.49              6.49
  2232            6.49              6.49
  2374            6.49              6.49
  2389            6.49              6.49
  2713            6.49              6.49
  2793            6.49              6.49
  2860            6.49              6.49
  3010            6.49              6.49
  3132            6.49              6.49
  3141            6.49              6.49
  3389           12.98              6.49
  3422            6.49              6.49
  3600            6.49              6.49
  3614            6.49              6.49
  3633            6.49              6.49
  3693            6.49              6.49
  3766            6.49              6.49
  3789            6.49              6.49
  3806            6.49              6.49
  3836            6.49              6.49
  3875            6.49              6.49
  3886            6.49              6.49
  4169            6.49              6.49
  4174            6.49              6.49
  4359            6.49              6.49
  4363            6.49              6.49
  4522            6.49              6.49
  4527            6.49              6.49
  4535            6.49              6.49  ),
 ('Barbacoa Bowl',
        order_id  quantity      item_name  \
  39          19         1  Barbacoa Bowl
  58          27         1  Barbacoa Bowl
  95          42         1  Barbacoa Bowl
  115         51         1  Barbacoa Bowl
  127         56         1  Barbacoa Bowl
  ...        ...       ...            ...
  4380      1748         1  Barbacoa Bowl
  4441      1770         1  Barbacoa Bowl
  4485      1786         1  Barbacoa Bowl
  4510      1793         1  Barbacoa Bowl
  4594      1825         1  Barbacoa Bowl

                                       choice_description item_price  \
  39    [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $11.75
  58    [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $11.75
  95    [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...     $9.25
  115   [[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...     $8.99
  127   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...     $9.25
  ...                                                 ...        ...
  4380  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.75
  4441  [Tomatillo Green Chili Salsa, [Rice, Cheese, G...    $11.75
  4485  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.75
  4510                                        [Guacamole]    $11.49
  4594  [Roasted Chili Corn Salsa, [Pinto Beans, Sour ...    $11.75

        itempricefloat  individual_price
  39             11.75             11.75
  58             11.75             11.75
  95              9.25              9.25
  115             8.99              8.99
  127             9.25              9.25
  ...              ...               ...
  4380           11.75             11.75
  4441           11.75             11.75
  4485           11.75             11.75
  4510           11.49             11.49
  4594           11.75             11.75

  [66 rows x 7 columns]),
 ('Barbacoa Burrito',
        order_id  quantity         item_name  \
  21          11         1  Barbacoa Burrito
  81          36         1  Barbacoa Burrito
  121         53         1  Barbacoa Burrito
  130         57         1  Barbacoa Burrito
  144         65         1  Barbacoa Burrito
  ...        ...       ...               ...
  4355      1739         1  Barbacoa Burrito
  4358      1740         1  Barbacoa Burrito
  4592      1825         1  Barbacoa Burrito
  4602      1827         1  Barbacoa Burrito
  4603      1827         1  Barbacoa Burrito

                                       choice_description item_price  \
  21    [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...     $8.99
  81    [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...     $9.25
  121   [Tomatillo Green Chili Salsa, [Rice, Black Bea...     $9.25
  130   [Roasted Chili Corn Salsa, [Rice, Pinto Beans,...    $11.75
  144   [Tomatillo Red Chili Salsa, [Rice, Sour Cream,...    $11.75
  ...                                                 ...        ...
  4355  [Roasted Chili Corn Salsa, [Fajita Vegetables,...    $11.75
  4358  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $9.25
  4592  [Tomatillo Red Chili Salsa, [Rice, Fajita Vege...    $11.75
  4602                      [Tomatillo Green Chili Salsa]     $9.25
  4603                      [Tomatillo Green Chili Salsa]     $9.25

        itempricefloat  individual_price
  21              8.99              8.99
  81              9.25              9.25
  121             9.25              9.25
  130            11.75             11.75
  144            11.75             11.75
  ...              ...               ...
  4355           11.75             11.75
  4358            9.25              9.25
  4592           11.75             11.75
  4602            9.25              9.25
  4603            9.25              9.25

  [91 rows x 7 columns]),
 ('Barbacoa Crispy Tacos',
        order_id  quantity              item_name  \
  168         75         1  Barbacoa Crispy Tacos
  255        110         1  Barbacoa Crispy Tacos
  429        186         1  Barbacoa Crispy Tacos
  485        205         1  Barbacoa Crispy Tacos
  763        315         1  Barbacoa Crispy Tacos
  829        343         1  Barbacoa Crispy Tacos
  1019       419         1  Barbacoa Crispy Tacos
  1866       756         1  Barbacoa Crispy Tacos
  1903       768         2  Barbacoa Crispy Tacos
  2787      1106         1  Barbacoa Crispy Tacos
  3321      1330         1  Barbacoa Crispy Tacos

                                       choice_description item_price  \
  168   [Tomatillo Red Chili Salsa, [Rice, Black Beans...    $11.75
  255   [Roasted Chili Corn Salsa, [Rice, Cheese, Lett...     $9.25
  429   [[Roasted Chili Corn Salsa (Medium), Tomatillo...    $11.48
  485                     [Fresh Tomato Salsa, Guacamole]    $11.75
  763         [Fresh Tomato Salsa, [Sour Cream, Lettuce]]     $9.25
  829   [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $9.25
  1019  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...     $8.99
  1866   [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]     $9.25
  1903   [Fresh Tomato Salsa, [Sour Cream, Cheese, Rice]]    $18.50
  2787  [Roasted Chili Corn Salsa, [Rice, Cheese, Lett...    $11.75
  3321  [[Fresh Tomato Salsa (Mild), Tomatillo-Green C...     $8.99

        itempricefloat  individual_price
  168            11.75             11.75
  255             9.25              9.25
  429            11.48             11.48
  485            11.75             11.75
  763             9.25              9.25
  829             9.25              9.25
  1019            8.99              8.99
  1866            9.25              9.25
  1903           18.50              9.25
  2787           11.75             11.75
  3321            8.99              8.99  ),
 ('Barbacoa Salad Bowl',
        order_id  quantity            item_name  \
  1229       501         1  Barbacoa Salad Bowl
  1326       541         1  Barbacoa Salad Bowl
  1418       576         1  Barbacoa Salad Bowl
  1421       576         1  Barbacoa Salad Bowl
  1825       738         1  Barbacoa Salad Bowl
  2442       970         1  Barbacoa Salad Bowl
  3208      1283         1  Barbacoa Salad Bowl
  3356      1346         1  Barbacoa Salad Bowl
  3546      1426         1  Barbacoa Salad Bowl
  4390      1751         1  Barbacoa Salad Bowl

                                       choice_description item_price  \
  1229  [Fresh Tomato Salsa, [Rice, Fajita Vegetables,...    $11.89
  1326  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.89
  1418                         [Roasted Chili Corn Salsa]     $9.39
  1421                         [Roasted Chili Corn Salsa]     $9.39
  1825  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...     $9.39
  2442  [Tomatillo Green Chili Salsa, [Rice, Fajita Ve...    $11.89
  3208  [Tomatillo Red Chili Salsa, [Black Beans, Chee...    $11.89
  3356  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...     $9.39
  3546                    [Fresh Tomato Salsa, Guacamole]    $11.89
  4390  [Tomatillo Green Chili Salsa, [Fajita Vegetabl...     $9.39

        itempricefloat  individual_price
  1229           11.89             11.89
  1326           11.89             11.89
  1418            9.39              9.39
  1421            9.39              9.39
  1825            9.39              9.39
  2442           11.89             11.89
  3208           11.89             11.89
  3356            9.39              9.39
  3546           11.89             11.89
  4390            9.39              9.39  ),
 ('Barbacoa Soft Tacos',
        order_id  quantity            item_name  \
  56          26         1  Barbacoa Soft Tacos
  181         82         1  Barbacoa Soft Tacos
  268        117         1  Barbacoa Soft Tacos
  611        252         1  Barbacoa Soft Tacos
  857        353         1  Barbacoa Soft Tacos
  988        406         1  Barbacoa Soft Tacos
  1129       467         1  Barbacoa Soft Tacos
  1149       475         1  Barbacoa Soft Tacos
  1240       506         1  Barbacoa Soft Tacos
  1334       545         1  Barbacoa Soft Tacos
  1391       565         1  Barbacoa Soft Tacos
  1642       663         1  Barbacoa Soft Tacos
  1669       675         1  Barbacoa Soft Tacos
  1754       708         1  Barbacoa Soft Tacos
  1985       803         1  Barbacoa Soft Tacos
  2083       841         1  Barbacoa Soft Tacos
  2248       906         1  Barbacoa Soft Tacos
  2259       910         1  Barbacoa Soft Tacos
  2434       966         1  Barbacoa Soft Tacos
  2780      1103         1  Barbacoa Soft Tacos
  3184      1273         1  Barbacoa Soft Tacos
  3211      1284         1  Barbacoa Soft Tacos
  3548      1426         1  Barbacoa Soft Tacos
  4182      1670         1  Barbacoa Soft Tacos
  4271      1703         1  Barbacoa Soft Tacos

                                       choice_description item_price  \
  56    [Fresh Tomato Salsa, [Fajita Vegetables, Black...     $9.25
  181   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...     $9.25
  268   [Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...     $8.99
  611   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...     $9.25
  857   [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...     $9.25
  988   [Tomatillo Red Chili Salsa, [Black Beans, Chee...    $11.75
  1129  [Roasted Chili Corn Salsa, [Rice, Pinto Beans,...    $11.75
  1149  [Tomatillo Green Chili Salsa, [Sour Cream, Che...     $9.25
  1240  [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...     $9.25
  1334  [Roasted Chili Corn Salsa, [Rice, Cheese, Sour...    $11.75
  1391  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...     $9.25
  1642  [[Fresh Tomato Salsa (Mild), Roasted Chili Cor...     $8.99
  1669  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...     $9.25
  1754  [Tomatillo Green Chili Salsa, [Pinto Beans, So...    $11.75
  1985  [Fresh Tomato Salsa, [Black Beans, Cheese, Let...     $9.25
  2083  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25
  2248  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...     $9.25
  2259  [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...     $9.25
  2434  [Roasted Chili Corn Salsa, [Cheese, Sour Cream...    $11.75
  2780  [Tomatillo Red Chili Salsa, [Rice, Pinto Beans...     $9.25
  3184  [Tomatillo-Red Chili Salsa (Hot), [Rice, Chees...    $11.48
  3211  [Roasted Chili Corn Salsa, [Rice, Black Beans,...    $11.75
  3548  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75
  4182  [Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...     $9.25
  4271  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $9.25

        itempricefloat  individual_price
  56              9.25              9.25
  181             9.25              9.25
  268             8.99              8.99
  611             9.25              9.25
  857             9.25              9.25
  988            11.75             11.75
  1129           11.75             11.75
  1149            9.25              9.25
  1240            9.25              9.25
  1334           11.75             11.75
  1391            9.25              9.25
  1642            8.99              8.99
  1669            9.25              9.25
  1754           11.75             11.75
  1985            9.25              9.25
  2083            9.25              9.25
  2248            9.25              9.25
  2259            9.25              9.25
  2434           11.75             11.75
  2780            9.25              9.25
  3184           11.48             11.48
  3211           11.75             11.75
  3548           11.75             11.75
  4182            9.25              9.25
  4271            9.25              9.25  ),
 ('Bottled Water',
        order_id  quantity      item_name choice_description item_price  \
  34          17         1  Bottled Water                NaN     $1.09
  87          38         1  Bottled Water                NaN     $1.09
  318        138         1  Bottled Water                NaN     $1.09
  329        143         1  Bottled Water                NaN     $1.50
  376        163         1  Bottled Water                NaN     $1.50
  ...        ...       ...            ...                ...        ...
  4568      1817         1  Bottled Water                NaN     $1.50
  4570      1817         1  Bottled Water                NaN     $1.50
  4582      1822         2  Bottled Water                NaN     $3.00
  4598      1826         1  Bottled Water                NaN     $1.50
  4614      1831         1  Bottled Water                NaN     $1.50

        itempricefloat  individual_price
  34              1.09              1.09
  87              1.09              1.09
  318             1.09              1.09
  329             1.50              1.50
  376             1.50              1.50
  ...              ...               ...
  4568            1.50              1.50
  4570            1.50              1.50
  4582            3.00              1.50
  4598            1.50              1.50
  4614            1.50              1.50

  [162 rows x 7 columns]),
 ('Bowl',
       order_id  quantity item_name  \
  445       193         3      Bowl
  673       279         1      Bowl

                                      choice_description item_price  \
  445  [Braised Carnitas, Pinto Beans, [Sour Cream, C...    $22.20
  673  [Adobo-Marinated and Grilled Steak, [Sour Crea...     $7.40

       itempricefloat  individual_price
  445            22.2               7.4
  673             7.4               7.4  ),
 ('Burrito',
       order_id  quantity item_name  \
  510       214         1   Burrito
  511       214         1   Burrito

### Step 7. ¿Cuantas veces se ha pedido los productos más caros?

In [114]:
data_sort=sorted(data.groupby("itempricefloat")["item_name"], reverse=True)
print(*data_sort)

(44.25, 3598    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object) (35.25, 3480    Carnitas Bowl
Name: item_name, dtype: object) (35.0, 1254    Chicken Burrito
3602    Chicken Burrito
Name: item_name, dtype: object) (33.75, 3601    Veggie Burrito
Name: item_name, dtype: object) (32.94, 409    Chicken Bowl
Name: item_name, dtype: object) (27.75, 1255    Steak Burrito
3603    Steak Burrito
Name: item_name, dtype: object) (26.25, 1514       Chicken Bowl
3634    Chicken Burrito
3636    Chicken Burrito
Name: item_name, dtype: object) (26.07, 3334    Steak Bowl
Name: item_name, dtype: object) (23.78, 281    Steak Salad Bowl
613    Steak Salad Bowl
Name: item_name, dtype: object) (23.5, 506     Carnitas Bowl
1566       Steak Bowl
1753    Steak Burrito
3754       Steak Bowl
4307       Steak Bowl
4427       Steak Bowl
Name: item_name, dtype: object) (22.96, 2954    Steak Burrito
Name: item_name, dtype: object) (22.5, 135     Chicken Salad Bowl
213     Chicken Salad Bowl
591     Chicken Salad Bowl
633     Chicken Salad Bowl
816     Chicken Salad Bowl
864     Chicken Salad Bowl
1110    Chicken Salad Bowl
1429          Chicken Bowl
1923    Chicken Salad Bowl
2419    Chicken Salad Bowl
2510          Chicken Bowl
3507    Chicken Salad Bowl
4423          Chicken Bowl
Name: item_name, dtype: object) (22.2, 445    Bowl
Name: item_name, dtype: object) (22.16, 353    Steak Burrito
549    Steak Burrito
Name: item_name, dtype: object) (21.96, 1718       Chicken Burrito
1832          Chicken Bowl
2075          Chicken Bowl
2525          Chicken Bowl
2942          Chicken Bowl
3151          Chicken Bowl
3331       Chicken Burrito
3508          Chicken Bowl
3658    Chicken Soft Tacos
3843          Chicken Bowl
Name: item_name, dtype: object) (18.5, 534             Steak Burrito
638             Steak Burrito
1903    Barbacoa Crispy Tacos
2581         Carnitas Burrito
3134            Steak Burrito
3354               Steak Bowl
3861            Steak Burrito
3970            Steak Burrito
4082               Steak Bowl
4232               Steak Bowl
4310            Steak Burrito
4354         Steak Soft Tacos
Name: item_name, dtype: object) (17.98, 148             Steak Burrito
910                Steak Bowl
1262            Steak Burrito
2380            Steak Burrito
2874       Steak Crispy Tacos
3616            Steak Burrito
3890    Carnitas Crispy Tacos
Name: item_name, dtype: object) (17.8, 4489    Chips and Guacamole
Name: item_name, dtype: object) (17.5, 150          Chicken Burrito
154             Chicken Bowl
217     Chicken Crispy Tacos
241          Chicken Burrito
282             Chicken Bowl
315       Chicken Salad Bowl
354       Chicken Soft Tacos
415             Chicken Bowl
426       Chicken Soft Tacos
654             Chicken Bowl
885     Chicken Crispy Tacos
976             Chicken Bowl
1017            Chicken Bowl
1106            Chicken Bowl
1166         Chicken Burrito
1219         Chicken Burrito
1434         Chicken Burrito
1588            Chicken Bowl
1656         Chicken Burrito
1845         Chicken Burrito
1981         Chicken Burrito
2045         Chicken Burrito
2051         Chicken Burrito
2061         Chicken Burrito
2106            Chicken Bowl
2589         Chicken Burrito
2598         Chicken Burrito
2637         Chicken Burrito
2953         Chicken Burrito
2975         Chicken Burrito
3167      Chicken Salad Bowl
3236         Chicken Burrito
3423            Chicken Bowl
3674         Chicken Burrito
3767         Chicken Burrito
3918         Chicken Burrito
4093         Chicken Burrito
4148         Chicken Burrito
4435            Chicken Bowl
4561      Chicken Salad Bowl
Name: item_name, dtype: object) (16.98, 4               Chicken Bowl
577       Chicken Soft Tacos
846              Veggie Bowl
2339            Chicken Bowl
2580            Chicken Bowl
2771            Chicken Bowl
3080            Chicken Bowl
3133            Chicken Bowl
3375         Chicken Burrito
3612            Chicken Bowl
3615         Chicken Burrito
3617             Veggie Bowl
3618            Chicken Bowl
3663            Chicken Bowl
3689         Chicken Burrito
3888      Chicken Soft Tacos
3889       Veggie Soft Tacos
3891    Chicken Crispy Tacos
3976            Chicken Bowl
Name: item_name, dtype: object) (16.38, 3823    Chicken Burrito
Name: item_name, dtype: object) (15.0, 4152    Bottled Water
Name: item_name, dtype: object) (13.52, 3887    Side of Chips
Name: item_name, dtype: object) (13.35, 2645    Chips and Guacamole
Name: item_name, dtype: object) (12.98, 3389    6 Pack Soft Drink
Name: item_name, dtype: object) (11.89, 606        Steak Salad Bowl
749        Steak Salad Bowl
1132    Carnitas Salad Bowl
1159       Steak Salad Bowl
1229    Barbacoa Salad Bowl
1311       Steak Salad Bowl
1326    Barbacoa Salad Bowl
1505       Steak Salad Bowl
1571       Steak Salad Bowl
1590       Steak Salad Bowl
1816       Steak Salad Bowl
2401       Steak Salad Bowl
2439       Steak Salad Bowl
2442    Barbacoa Salad Bowl
2610    Carnitas Salad Bowl
2740       Steak Salad Bowl
2804       Steak Salad Bowl
2957       Steak Salad Bowl
3120       Steak Salad Bowl
3208    Barbacoa Salad Bowl
3350       Steak Salad Bowl
3493       Steak Salad Bowl
3546    Barbacoa Salad Bowl
3749    Carnitas Salad Bowl
4239    Carnitas Salad Bowl
4313       Steak Salad Bowl
Name: item_name, dtype: object) (11.8, 1257    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object) (11.75, 7       Steak Burrito
39      Barbacoa Bowl
43      Steak Burrito
58      Barbacoa Bowl
90         Steak Bowl
            ...
4594    Barbacoa Bowl
4607    Steak Burrito
4610    Steak Burrito
4617    Steak Burrito
4618    Steak Burrito
Name: item_name, Length: 284, dtype: object) (11.49, 4510    Barbacoa Bowl
Name: item_name, dtype: object) (11.48, 147             Steak Burrito
163             Carnitas Bowl
177             Steak Burrito
187                Steak Bowl
412                Steak Bowl
428                Steak Bowl
429     Barbacoa Crispy Tacos
471             Barbacoa Bowl
595                Steak Bowl
649             Steak Burrito
712             Steak Burrito
862             Steak Burrito
1042               Steak Bowl
1063         Carnitas Burrito
1072            Steak Burrito
1093            Steak Burrito
1144            Steak Burrito
1148               Steak Bowl
1174            Barbacoa Bowl
1175            Barbacoa Bowl
1235            Barbacoa Bowl
1236            Barbacoa Bowl
1275            Steak Burrito
1276            Steak Burrito
1321            Steak Burrito
1354               Steak Bowl
1383            Barbacoa Bowl
1384            Steak Burrito
1430            Carnitas Bowl
1461               Steak Bowl
1721         Steak Soft Tacos
2008            Steak Burrito
2009            Steak Burrito
2233            Carnitas Bowl
2236            Steak Burrito
2239         Carnitas Burrito
2488            Carnitas Bowl
2547            Carnitas Bowl
2767            Steak Burrito
3016               Steak Bowl
3094            Steak Burrito
3103            Carnitas Bowl
3105         Steak Soft Tacos
3184      Barbacoa Soft Tacos
3204            Steak Burrito
3273            Steak Burrito
3276         Barbacoa Burrito
3339            Steak Burrito
3625         Steak Soft Tacos
3792            Carnitas Bowl
3865               Steak Bowl
Name: item_name, dtype: object) (11.25, 13            Chicken Bowl
42            Chicken Bowl
57          Veggie Burrito
62             Veggie Bowl
79      Chicken Soft Tacos
               ...
4589          Chicken Bowl
4590          Chicken Bowl
4608        Veggie Burrito
4611        Veggie Burrito
4619    Chicken Salad Bowl
Name: item_name, Length: 521, dtype: object) (11.08, 322        Steak Burrito
822        Carnitas Bowl
825           Steak Bowl
1293          Steak Bowl
1294       Carnitas Bowl
1648    Barbacoa Burrito
1740       Carnitas Bowl
2884    Carnitas Burrito
3140       Steak Burrito
3251       Steak Burrito
Name: item_name, dtype: object) (10.98, 5          Chicken Bowl
23      Chicken Burrito
45      Chicken Burrito
52      Chicken Burrito
68      Chicken Burrito
             ...
3742       Chicken Bowl
3794    Chicken Burrito
3908       Chicken Bowl
3967    Chicken Burrito
4077       Chicken Bowl
Name: item_name, Length: 99, dtype: object) (10.58, 476     Chicken Burrito
1099    Chicken Burrito
1160    Chicken Burrito
2919       Chicken Bowl
3520    Chicken Burrito
Name: item_name, dtype: object) (10.5, 3599    Bottled Water
Name: item_name, dtype: object) (9.39, 607        Steak Salad Bowl
1418    Barbacoa Salad Bowl
1421    Barbacoa Salad Bowl
1825    Barbacoa Salad Bowl
1865    Carnitas Salad Bowl
2600       Steak Salad Bowl
2624       Steak Salad Bowl
3098       Steak Salad Bowl
3115    Carnitas Salad Bowl
3356    Barbacoa Salad Bowl
4036       Steak Salad Bowl
4241       Steak Salad Bowl
4390    Barbacoa Salad Bowl
4391       Steak Salad Bowl
4419       Steak Salad Bowl
4547       Steak Salad Bowl
4572       Steak Salad Bowl
Name: item_name, dtype: object) (9.25, 8          Steak Soft Tacos
9             Steak Burrito
56      Barbacoa Soft Tacos
61         Steak Soft Tacos
81         Barbacoa Burrito
               ...
4562          Carnitas Bowl
4578       Carnitas Burrito
4602       Barbacoa Burrito
4603       Barbacoa Burrito
4612          Carnitas Bowl
Name: item_name, Length: 398, dtype: object) (8.99, 21      Barbacoa Burrito
27      Carnitas Burrito
31         Steak Burrito
33         Carnitas Bowl
46         Steak Burrito
              ...
4054          Steak Bowl
4089       Steak Burrito
4267          Steak Bowl
4268       Steak Burrito
4508       Steak Burrito
Name: item_name, Length: 246, dtype: object) (8.9, 792     Chips and Guacamole
880     Chips and Guacamole
978     Chips and Guacamole
1258    Chips and Guacamole
1346    Chips and Guacamole
1351    Chips and Guacamole
1423    Chips and Guacamole
1824    Chips and Guacamole
1881    Chips and Guacamole
1978    Chips and Guacamole
2019    Chips and Guacamole
2036    Chips and Guacamole
2251    Chips and Guacamole
2453    Chips and Guacamole
2608    Chips and Guacamole
2859    Chips and Guacamole
3066    Chips and Guacamole
3158    Chips and Guacamole
3791    Chips and Guacamole
4332    Chips and Guacamole
Name: item_name, dtype: object) (8.75, 11      Chicken Crispy Tacos
12        Chicken Soft Tacos
19              Chicken Bowl
35        Chicken Soft Tacos
36        Chicken Soft Tacos
                ...
4599            Chicken Bowl
4604            Chicken Bowl
4615      Chicken Soft Tacos
4620      Chicken Salad Bowl
4621      Chicken Salad Bowl
Name: item_name, Length: 730, dtype: object) (8.69, 728          Steak Burrito
729     Steak Crispy Tacos
926             Steak Bowl
1272         Steak Burrito
3156      Barbacoa Burrito
3195         Barbacoa Bowl
3196            Steak Bowl
3252      Carnitas Burrito
3501         Steak Burrito
3502           Steak Salad
3529      Carnitas Burrito
3530         Steak Burrito
3532         Steak Burrito
3540         Steak Burrito
3822         Barbacoa Bowl
3902      Barbacoa Burrito
3988         Steak Burrito
4056         Barbacoa Bowl
4068         Steak Burrito
Name: item_name, dtype: object) (8.5, 4235           Chicken Bowl
4236           Chicken Bowl
4237    Chips and Guacamole
Name: item_name, dtype: object) (8.49, 16      Chicken Burrito
17      Chicken Burrito
26         Chicken Bowl
29      Chicken Burrito
85          Veggie Bowl
             ...
4071       Chicken Bowl
4075       Chicken Bowl
4083     Veggie Burrito
4084       Veggie Salad
4087       Chicken Bowl
Name: item_name, Length: 311, dtype: object) (8.19, 1161    Chicken Burrito
1271    Chicken Burrito
2918       Chicken Bowl
3101       Chicken Bowl
3139    Chicken Burrito
3519    Chicken Burrito
3539    Chicken Burrito
3664       Chicken Bowl
3824    Chicken Burrito
3903    Chicken Burrito
3987    Chicken Burrito
3989      Chicken Salad
3990    Chicken Burrito
4067    Chicken Burrito
Name: item_name, dtype: object) (7.98, 3040    Chips and Guacamole
Name: item_name, dtype: object) (7.5, 2441    Bottled Water
Name: item_name, dtype: object) (7.4, 510          Burrito
511          Burrito
519          Burrito
520     Crispy Tacos
521     Crispy Tacos
673             Bowl
675          Burrito
759          Burrito
760          Burrito
1414           Salad
1415           Salad
Name: item_name, dtype: object) (7.17, 2972    Chips and Tomatillo-Red Chili Salsa
3270    Chips and Tomatillo-Red Chili Salsa
Name: item_name, dtype: object) (6.78, 601     Nantucket Nectar
2379    Nantucket Nectar
Name: item_name, dtype: object) (6.49, 298     6 Pack Soft Drink
341     6 Pack Soft Drink
357     6 Pack Soft Drink
388     6 Pack Soft Drink
417     6 Pack Soft Drink
553     6 Pack Soft Drink
639     6 Pack Soft Drink
721     6 Pack Soft Drink
743     6 Pack Soft Drink
879     6 Pack Soft Drink
1026    6 Pack Soft Drink
1051    6 Pack Soft Drink
1124    6 Pack Soft Drink
1167    6 Pack Soft Drink
1260    6 Pack Soft Drink
1279    6 Pack Soft Drink
1392    6 Pack Soft Drink
1755    6 Pack Soft Drink
1758    6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
1916    6 Pack Soft Drink
1922    6 Pack Soft Drink
1937    6 Pack Soft Drink
1976    6 Pack Soft Drink
2108    6 Pack Soft Drink
2232    6 Pack Soft Drink
2374    6 Pack Soft Drink
2389    6 Pack Soft Drink
2713    6 Pack Soft Drink
2793    6 Pack Soft Drink
2860    6 Pack Soft Drink
3010    6 Pack Soft Drink
3132    6 Pack Soft Drink
3141    6 Pack Soft Drink
3422    6 Pack Soft Drink
3600    6 Pack Soft Drink
3614    6 Pack Soft Drink
3633    6 Pack Soft Drink
3693    6 Pack Soft Drink
3766    6 Pack Soft Drink
3789    6 Pack Soft Drink
3806    6 Pack Soft Drink
3836    6 Pack Soft Drink
3875    6 Pack Soft Drink
3886    6 Pack Soft Drink
4169    6 Pack Soft Drink
4174    6 Pack Soft Drink
4359    6 Pack Soft Drink
4363    6 Pack Soft Drink
4522    6 Pack Soft Drink
4527    6 Pack Soft Drink
4535    6 Pack Soft Drink
Name: item_name, dtype: object) (6.45, 2936    Chips
Name: item_name, dtype: object) (6.0, 1425    Bottled Water
1880    Bottled Water
Name: item_name, dtype: object) (5.9, 235     Chips and Tomatillo Green Chili Salsa
1259    Chips and Tomatillo Green Chili Salsa
1555       Chips and Roasted Chili Corn Salsa
1620      Chips and Tomatillo Red Chili Salsa
1882             Chips and Fresh Tomato Salsa
2267             Chips and Fresh Tomato Salsa
2729             Chips and Fresh Tomato Salsa
4312      Chips and Tomatillo Red Chili Salsa
Name: item_name, dtype: object) (5.07, 2944    Side of Chips
Name: item_name, dtype: object) (5.0, 3973    Canned Soft Drink
4490    Canned Soft Drink
4491    Canned Soft Drink
Name: item_name, dtype: object) (4.78, 2550      Chips and Tomatillo-Red Chili Salsa
2656    Chips and Tomatillo-Green Chili Salsa
3657    Chips and Tomatillo-Green Chili Salsa
Name: item_name, dtype: object) (4.5, 3294    Bottled Water
3314    Bottled Water
4137    Bottled Water
4186    Bottled Water
Name: item_name, dtype: object) (4.45, 10      Chips and Guacamole
14      Chips and Guacamole
20      Chips and Guacamole
37      Chips and Guacamole
41      Chips and Guacamole
               ...
4588    Chips and Guacamole
4596    Chips and Guacamole
4600    Chips and Guacamole
4605    Chips and Guacamole
4616    Chips and Guacamole
Name: item_name, Length: 349, dtype: object) (4.36, 2235    Canned Soda
Name: item_name, dtype: object) (4.3, 223     Chips
828     Chips
1301    Chips
1600    Chips
1605    Chips
1850    Chips
1900    Chips
2112    Chips
2258    Chips
2343    Chips
2421    Chips
2746    Chips
3291    Chips
3932    Chips
4126    Chips
4389    Chips
4417    Chips
Name: item_name, dtype: object) (4.0, 676     Chips and Guacamole
1416    Chips and Guacamole
Name: item_name, dtype: object) (3.99, 49      Chips and Guacamole
72      Chips and Guacamole
103     Chips and Guacamole
119     Chips and Guacamole
201     Chips and Guacamole
               ...
3942    Chips and Guacamole
3952    Chips and Guacamole
4006    Chips and Guacamole
4029    Chips and Guacamole
4076    Chips and Guacamole
Name: item_name, Length: 98, dtype: object) (3.89, 927     Chips and Guacamole
1295    Chips and Guacamole
1647    Chips and Guacamole
3531    Chips and Guacamole
3665    Chips and Guacamole
3825    Chips and Guacamole
Name: item_name, dtype: object) (3.75, 689     Canned Soft Drink
850     Canned Soft Drink
917     Canned Soft Drink
1559    Canned Soft Drink
3089    Canned Soft Drink
3128    Canned Soft Drink
4098    Canned Soft Drink
Name: item_name, dtype: object) (3.39, 1                   Izze
2       Nantucket Nectar
22      Nantucket Nectar
24                  Izze
47                  Izze
66                  Izze
105     Nantucket Nectar
173     Nantucket Nectar
205     Nantucket Nectar
359                 Izze
360                 Izze
430                 Izze
436     Nantucket Nectar
579                 Izze
580                 Izze
925     Nantucket Nectar
1059                Izze
1213                Izze
1356    Nantucket Nectar
1585    Nantucket Nectar
1611                Izze
1612                Izze
1626    Nantucket Nectar
1680                Izze
1706    Nantucket Nectar
2088                Izze
2162    Nantucket Nectar
2381    Nantucket Nectar
2430    Nantucket Nectar
2619                Izze
2634                Izze
2653    Nantucket Nectar
2758                Izze
2818    Nantucket Nectar
2838    Nantucket Nectar
2853    Nantucket Nectar
2891                Izze
2949    Nantucket Nectar
3318    Nantucket Nectar
3368    Nantucket Nectar
3570    Nantucket Nectar
3669                Izze
3845    Nantucket Nectar
4019    Nantucket Nectar
4078    Nantucket Nectar
Name: item_name, dtype: object) (3.27, 818     Bottled Water
2823    Bottled Water
Name: item_name, dtype: object) (3.0, 540                         Bottled Water
674     Chips and Mild Fresh Tomato Salsa
889                         Bottled Water
1988                        Bottled Water
2068                        Bottled Water
2458                        Bottled Water
2623                        Bottled Water
3604                        Bottled Water
3783                        Bottled Water
4582                        Bottled Water
Name: item_name, dtype: object) (2.95, 38      Chips and Tomatillo Green Chili Salsa
89               Chips and Fresh Tomato Salsa
111       Chips and Tomatillo Red Chili Salsa
128       Chips and Tomatillo Red Chili Salsa
183              Chips and Fresh Tomato Salsa
                        ...
4425             Chips and Fresh Tomato Salsa
4466      Chips and Tomatillo Red Chili Salsa
4476    Chips and Tomatillo Green Chili Salsa
4493    Chips and Tomatillo Green Chili Salsa
4503             Chips and Fresh Tomato Salsa
Name: item_name, Length: 174, dtype: object) (2.5, 492     Canned Soft Drink
651     Canned Soft Drink
791     Canned Soft Drink
1338    Canned Soft Drink
1373    Canned Soft Drink
1377    Canned Soft Drink
1412    Canned Soft Drink
1760    Canned Soft Drink
1878    Canned Soft Drink
1879    Canned Soft Drink
2274    Canned Soft Drink
2513    Canned Soft Drink
2766    Canned Soft Drink
2995    Canned Soft Drink
3018    Canned Soft Drink
3135    Canned Soft Drink
3159    Canned Soft Drink
3242    Canned Soft Drink
3418    Canned Soft Drink
3524    Canned Soft Drink
3609    Canned Soft Drink
3699    Canned Soft Drink
3880    Canned Soft Drink
4016    Canned Soft Drink
4027    Canned Soft Drink
4499    Canned Soft Drink
4560    Canned Soft Drink
Name: item_name, dtype: object) (2.39, 0                Chips and Fresh Tomato Salsa
3       Chips and Tomatillo-Green Chili Salsa
15      Chips and Tomatillo-Green Chili Salsa
25               Chips and Fresh Tomato Salsa
30      Chips and Tomatillo-Green Chili Salsa
                        ...
3907             Chips and Fresh Tomato Salsa
3983             Chips and Fresh Tomato Salsa

### Step 8. Veamos para el caso de Veggie Salad Bowl. Extrae esa información.

In [110]:
condicion=(data["item_name"]=="Veggie Salad Bowl")

data[condicion]

,order_id,quantity,item_name,choice_description,item_price,itempricefloat,individual_price
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25,11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$11.25,11.25,11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25,11.25
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",$11.25,11.25,11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75,8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75,8.75
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25,11.25
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25,11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",$8.75,8.75,8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75,8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75,8.75
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25,11.25
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75,8.75
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25,11.25
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$11.25,11.25,11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25,11.25
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75,8.75
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75,8.75